# Generated by Django 4.1.4 on 2023-05-04 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coinbasepayment',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Pending'), (2, 'Success'), (3, 'Failed')], default=1),
        ),
        migrations.AlterField(
            model_name='coinbasepayment',
            name='uuid',
            field=models.UUIDField(unique=True),
        ),
    ]
