# Generated by Django 4.1.4 on 2023-05-07 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('payments', '0002_coinbasepayment_status_alter_coinbasepayment_uuid'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CoinbasePayment',
            new_name='BalanceTopUpViaCoinbase',
        ),
    ]
