# Generated by Django 4.1.4 on 2023-05-07 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('payments', '0003_rename_coinbasepayment_balancetopupviacoinbase'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoinbasePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(unique=True)),
                ('payment_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Pending'), (2, 'Success'), (3, 'Failed')], default=1)),
                ('type', models.PositiveSmallIntegerField(choices=[(1, 'Balance Top Up'), (2, 'Payment For Order')])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.user')),
            ],
        ),
        migrations.DeleteModel(
            name='BalanceTopUpViaCoinbase',
        ),
    ]
