# Generated by Django 4.1.4 on 2023-05-07 08:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_coinbasepayment_delete_balancetopupviacoinbase'),
    ]

    operations = [
        migrations.AddField(
            model_name='coinbasepayment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
