# Generated by Django 4.1.4 on 2023-01-04 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_alter_user_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Open'), (2, 'Pending'), (3, 'On Hold'), (4, 'Closed')], default=1)),
                ('issue', models.TextField(max_length=4096)),
                ('answer', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.user')),
            ],
        ),
        migrations.CreateModel(
            name='ReplyToTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue', models.CharField(max_length=4096)),
                ('answer', models.CharField(max_length=4096)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='support.supportticket')),
            ],
        ),
    ]
