# Generated by Django 4.1.4 on 2023-01-01 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supportrequest',
            name='is_open',
        ),
        migrations.AddField(
            model_name='supportrequest',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Open'), (2, 'Pending'), (3, 'On Hold'), (4, 'Closed')], default=1),
        ),
    ]
