# Generated by Django 4.1.4 on 2023-01-04 13:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='replytoticket',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='replytoticket',
            name='answer',
            field=models.CharField(blank=True, max_length=4096, null=True),
        ),
    ]
