# Generated by Django 4.1.4 on 2023-01-01 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_options'),
        ('support', '0002_remove_supportrequest_is_open_supportrequest_status'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SupportRequest',
            new_name='SupportTicket',
        ),
    ]
