# Generated by Django 4.1.4 on 2023-01-01 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0003_rename_supportrequest_supportticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportticket',
            name='subject',
            field=models.CharField(max_length=64),
        ),
        migrations.DeleteModel(
            name='SupportSubject',
        ),
    ]
