# Generated by Django 4.1.4 on 2023-01-01 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0004_alter_supportticket_subject_delete_supportsubject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportticket',
            name='issue',
            field=models.TextField(max_length=4096),
        ),
    ]
