# Generated by Django 4.1.4 on 2023-01-05 04:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_productpicture_remove_product_picture_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productpicture',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='products.product'),
            preserve_default=False,
        ),
    ]
