# Generated by Django 4.1.4 on 2022-12-25 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_picture_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='picture_url',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
