# Generated by Django 4.1.4 on 2023-04-29 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_rename_is_stocks_displayed_product_are_stocks_displayed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='emoji_icon',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
