# Generated by Django 4.1.4 on 2023-04-29 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_category_emoji_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_balance_only',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='category',
            name='priority',
            field=models.PositiveSmallIntegerField(help_text='the bigger number the higher priority'),
        ),
    ]
