# Generated by Django 4.1.4 on 2023-04-29 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_is_balance_only_alter_category_priority'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productpicture',
            name='picture',
        ),
        migrations.AddField(
            model_name='productpicture',
            name='url',
            field=models.URLField(default='https://i.imgur.com/zkayFUO.png'),
            preserve_default=False,
        ),
    ]
