# Generated by Django 4.1.4 on 2022-12-26 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_order_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='picture_url',
            field=models.ImageField(blank=True, null=True, upload_to='pictures'),
        ),
    ]
