# Generated by Django 4.1.4 on 2022-12-28 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_product_picture_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='quantity',
            new_name='stocks_count',
        ),
    ]
