# Generated by Django 4.1.4 on 2023-04-29 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_remove_productpicture_picture_productpicture_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='content',
        ),
    ]
