# Generated by Django 4.1.4 on 2023-01-01 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_category_priority_alter_category_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='priority',
            field=models.PositiveSmallIntegerField(help_text='the smaller number the higher priority'),
        ),
    ]
